[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[context.production.environment]
  VITE_API_URL = "https://invoice-backend.atologbook.workers.dev/api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy/:splat"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    X-Frame-Options = "DENY"